version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - .:/var/www
    links:
      - db
    entrypoint:
      DB_DRIVER: pgsql
      DB_HOST: db
      DB_NAME: project
      DB_USER: roman
      DB_PASSWORD: chernykh

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 81:80
    links:
      - backend
    environment:
      - FPM_UPSTREAM=backend:9000
      - APP_ENTRYPOINT=/var/www/public/index.php

  db:
    image: postgres:12-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=roman
      - POSTGRES_PASSWORD=chernykh